### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [MarietjeVL/Colmar#3]
Exceeds Expectations

Very happy with this project one of the best capstones I've seen, it looks similar to spec but much improved upon. I looked through your flex use and you did a great job on them, in the courses section, you had align-items stretch which I am not sure if it was needed.  DRY or Don't Repeat Yourself Code is when you reuse code blocks so you don't have to type it over and over, basically the idea behind classes. If you look at the spec, sections 1,2 and 4 are the same, 60% on the left, 40% on the right, with a media container on the left. You can make classes and reuse them for this, try it out.Next, try to add a few more pages, maybe a form for sign in, some of the other pages, you can use w3schools.com for forms guide. unsplash.com or freepik.com for images and themeforest.com for web layout ideas. If you make this a full site you can add this as a great portfolio piece. Keep up the good work.

**Comment by MarietjeVL** [comment]
Thank you!!

It took me some time to figure out the flexbox (I am used to bootstrap) but I think I can finally manage myself. There are still a few things/situations that I am not completely certain about but I guess it will take some practise! I will try to think about some extra pages. Thank you for the review.
